### ISSUE TITLE
dropEst ERROR: unable to parse out UMI

### ISSUE THREAD

**Issue by jhe2020** [hms-dbmi/dropEst#97]
Hello, I'm trying dropEst on 10x 3' GEX v3.1 data for the first time. I'm getting unable to parse out UMI errors. I'm not sure what the problem is. Does the config file need to be modified? The input is a bam file from CellRanger count. Code is as follows. Thanks ahead of time for your help. 

~/build/bin/dropest -m -F -L eiEIBA -o run1 -g ~/mm10/genes/genes.gtf -c ~/dropEst/configs/indrop_v3.xml ~/outs/possorted_genome_bam.bam

**Comment by chlee-tabin** [comment]
The configs file should be 10x.xml rather than indrop_v3.xml.

Also, if it is v3, then see also https://github.com/hms-dbmi/dropEst/issues/90

**Comment by mangospa** [comment]
I tried 10x.xml and specified <umi_length>12</umi_length>
But I still get the same errors
The data is from 10x v3.1

**Comment by chlee-tabin** [comment]
@mangospa I think you do not need to do additional UMI merge (-m), but this is my usage of dropEst. (I cannot find the exact thread in the issue section, but I remember there was a discussion about the UMI merge and cellranger is doing it reasonably).

**Comment by VPetukhov** [comment]
@mangospa When you run `dropest` only `Estimation` section of the config matters. So, `umi_length` doesn't play any role. Most probably the problem is in bam tags. Please check [`BamTag`](https://github.com/hms-dbmi/dropEst/blob/master/configs/config_desc.xml#L68) section in the config and ensure that tags in the config correspond to those in the bam.

@chlee-tabin , thanks for answering the question! Small correction: `-m` is the barcode merge, and `-u` is the UMI merge. Nevertheless, you're right and there is no reason to use it with 10x bam file.
